pr:
  branches:
    include:
      - master  # Trigger pipeline on PR targeting the 'master' branch

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
stages:
- stage: build
  displayName: 'Build stage'
  jobs:
  - job: build
    displayName: 'Build stage'
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    # Publish artifact step to make the zip file available to the next stage
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'WebAppArtifact'
        targetPath: '$(build.artifactStagingDirectory)'

# Deploy Stage, runs only if NOT a PR trigger
- stage: Deploy
  displayName: 'Deploy Stage'
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'refs/pull/'))
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
      # Download the artifact (make sure the artifact name matches)
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          downloadPath: '$(System.ArtifactsDirectory)'
          artifactName: 'WebAppArtifact'  # Make sure this matches the artifact name used in the build stage

      # Azure Web App Deployment
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Free Trial(35c05a47-103a-44b2-8f45-0e9355285917)'  # Ensure subscription name is correct
          appType: 'webApp'
          WebAppName: 'demosaiappweb'
          packageForLinux: '$(System.ArtifactsDirectory)/WebAppArtifact/**/*.zip'  # Correct the path to point to the downloaded zip file
